
version: '3'
services:
  rabbitMQ:
   image: rabbitmq:3-management
   container_name: 'rabbitmq_container'
   environment:
    - RABBITMQ_DEFAULT_USER=guest
    - RABBITMQ_DEFAULT_PASS=guest
   ports:
    - 8050:15672
    - 5672:5672
   expose:
    - 5672
   networks: 
    - oftamoloskanet2025
    
  oftamoloska_sql:
    container_name: app_db
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Word5678?
      - MSSQL_PID=Developer
    ports:
      - 1405:1433
    expose:
      - 1433
    networks:
      - oftamoloskanet2025

  oftamoloska_api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:DefaultConnection=Server=oftamoloska_sql, 1433;Database=OftamoloskiCentar;User=sa;Password=Word5678?;ConnectRetryCount=0;TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5116:5116
    networks:
      - oftamoloskanet2025
    links:
      - oftamoloska_sql
    depends_on:
      - oftamoloska_sql


  dodatni_api:
    restart: unless-stopped
    build:
      context: ../OftamoloskaDodatni
    environment:
      - ConnectionStrings:DefaultConnection=Server=oftamoloska_sql, 1433;Database=OftamoloskiCentar;User=sa;Password=Word5678?;ConnectRetryCount=0;TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ_HOST=rabbitMQ
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_VIRTUALHOST=/
    ports:
      - 5278:5278
    networks:
      - oftamoloskanet2025
    depends_on:
      - rabbitMQ
      
    
    
  
networks:
  oftamoloskanet2025:
    driver: bridge
